version: '3'
services:
  web:
    build: .
    ports: 
      - '9292:9292'
    links: 
      - 'redis'
    depends_on: 
      - 'redis'
    command: rackup
  sidekiq:
    build: .
    links: 
      - 'redis'
    depends_on: 
      - 'redis'
    environment:
      REDIS_PROVIDER: 'redis'
    command: sidekiq -r ./sidekiq.rb
  redis:
    image: 'redis:alpine'
