version: '3'
services:
  web:
    build: .
    ports: 
      - '9292:9292'
    links: 
      - 'redis'
    depends_on: 
      - 'redis'
    environment:
      REDIS_PROVIDER: REDIS_ADDR
      REDIS_ADDR: 'redis://redis'
      RACK_ENV: 'production'
      JRUBY_OPTS: '-Xcompile.invokedynamic=true'
    command: rackup -o 0.0.0.0
  sidekiq:
    build: .
    links: 
      - 'redis'
    depends_on: 
      - 'redis'
    environment:
      REDIS_PROVIDER: REDIS_ADDR
      REDIS_ADDR: 'redis://redis'
      JRUBY_OPTS: '-Xcompile.invokedynamic=true'
    command: sidekiq -e production -r ./sidekiq.rb
  redis:
    image: 'redis:alpine'
